import { Surah, DalilTopic } from './types';

export const SURAH_DATA: Surah[] = [
  { number: 1, latin: "Al-Fatihah", name: "الفاتحة", meaning: "Pembukaan", ayahs: 7, juz: 1, type: "Makkiyah" },
  { number: 2, latin: "Al-Baqarah", name: "البقرة", meaning: "Sapi Betina", ayahs: 286, juz: 1, type: "Madaniyah" },
  { number: 3, latin: "Ali 'Imran", name: "آل عمران", meaning: "Keluarga Imran", ayahs: 200, juz: 3, type: "Madaniyah" },
  { number: 4, latin: "An-Nisa'", name: "النساء", meaning: "Wanita", ayahs: 176, juz: 4, type: "Madaniyah" },
  { number: 5, latin: "Al-Ma'idah", name: "المائدة", meaning: "Hidangan", ayahs: 120, juz: 6, type: "Madaniyah" },
  { number: 6, latin: "Al-An'am", name: "الأنعام", meaning: "Binatang Ternak", ayahs: 165, juz: 7, type: "Makkiyah" },
  { number: 7, latin: "Al-A'raf", name: "الأعراف", meaning: "Tempat Tertinggi", ayahs: 206, juz: 8, type: "Makkiyah" },
  { number: 8, latin: "Al-Anfal", name: "الأنفال", meaning: "Harta Rampasan Perang", ayahs: 75, juz: 9, type: "Madaniyah" },
  { number: 9, latin: "At-Taubah", name: "التوبة", meaning: "Pengampunan", ayahs: 129, juz: 10, type: "Madaniyah" },
  { number: 10, latin: "Yunus", name: "يونس", meaning: "Nabi Yunus", ayahs: 109, juz: 11, type: "Makkiyah" },
  { number: 11, latin: "Hud", name: "هود", meaning: "Nabi Hud", ayahs: 123, juz: 11, type: "Makkiyah" },
  { number: 12, latin: "Yusuf", name: "يوسف", meaning: "Nabi Yusuf", ayahs: 111, juz: 12, type: "Makkiyah" },
  { number: 13, latin: "Ar-Ra'd", name: "الرعد", meaning: "Guruh", ayahs: 43, juz: 13, type: "Madaniyah" },
  { number: 14, latin: "Ibrahim", name: "ابراهيم", meaning: "Nabi Ibrahim", ayahs: 52, juz: 13, type: "Makkiyah" },
  { number: 15, latin: "Al-Hijr", name: "الحجر", meaning: "Gunung Batu", ayahs: 99, juz: 14, type: "Makkiyah" },
  { number: 16, latin: "An-Nahl", name: "النحل", meaning: "Lebah", ayahs: 128, juz: 14, type: "Makkiyah" },
  { number: 17, latin: "Al-Isra'", name: "الإسراء", meaning: "Perjalanan Malam", ayahs: 111, juz: 15, type: "Makkiyah" },
  { number: 18, latin: "Al-Kahf", name: "الكهف", meaning: "Penghuni Gua", ayahs: 110, juz: 15, type: "Makkiyah" },
  { number: 19, latin: "Maryam", name: "مريم", meaning: "Maryam", ayahs: 98, juz: 16, type: "Makkiyah" },
  { number: 20, latin: "Taha", name: "طه", meaning: "Taha", ayahs: 135, juz: 16, type: "Makkiyah" },
  { number: 21, latin: "Al-Anbiya'", name: "الأنبياء", meaning: "Nabi-Nabi", ayahs: 112, juz: 17, type: "Makkiyah" },
  { number: 22, latin: "Al-Hajj", name: "الحج", meaning: "Haji", ayahs: 78, juz: 17, type: "Madaniyah" },
  { number: 23, latin: "Al-Mu'minun", name: "المؤمنون", meaning: "Orang-Orang Mukmin", ayahs: 118, juz: 18, type: "Makkiyah" },
  { number: 24, latin: "An-Nur", name: "النور", meaning: "Cahaya", ayahs: 64, juz: 18, type: "Madaniyah" },
  { number: 25, latin: "Al-Furqan", name: "الفرقان", meaning: "Pembeda", ayahs: 77, juz: 18, type: "Makkiyah" },
  { number: 26, latin: "Asy-Syu'ara'", name: "الشعراء", meaning: "Para Penyair", ayahs: 227, juz: 19, type: "Makkiyah" },
  { number: 27, latin: "An-Naml", name: "النمل", meaning: "Semut", ayahs: 93, juz: 19, type: "Makkiyah" },
  { number: 28, latin: "Al-Qasas", name: "القصص", meaning: "Kisah-Kisah", ayahs: 88, juz: 20, type: "Makkiyah" },
  { number: 29, latin: "Al-Ankabut", name: "العنكبوت", meaning: "Laba-Laba", ayahs: 69, juz: 20, type: "Makkiyah" },
  { number: 30, latin: "Ar-Rum", name: "الروم", meaning: "Bangsa Romawi", ayahs: 60, juz: 21, type: "Makkiyah" },
  { number: 31, latin: "Luqman", name: "لقمان", meaning: "Luqman", ayahs: 34, juz: 21, type: "Makkiyah" },
  { number: 32, latin: "As-Sajdah", name: "السجدة", meaning: "Sajdah", ayahs: 30, juz: 21, type: "Makkiyah" },
  { number: 33, latin: "Al-Ahzab", name: "الأحزاب", meaning: "Golongan Bersekutu", ayahs: 73, juz: 21, type: "Madaniyah" },
  { number: 34, latin: "Saba'", name: "سبأ", meaning: "Kaum Saba'", ayahs: 54, juz: 22, type: "Makkiyah" },
  { number: 35, latin: "Fatir", name: "فاطر", meaning: "Pencipta", ayahs: 45, juz: 22, type: "Makkiyah" },
  { number: 36, latin: "Ya Sin", name: "يس", meaning: "Ya Sin", ayahs: 83, juz: 22, type: "Makkiyah" },
  { number: 37, latin: "As-Saffat", name: "الصافات", meaning: "Yang Bershaf-Shaf", ayahs: 182, juz: 23, type: "Makkiyah" },
  { number: 38, latin: "Sad", name: "ص", meaning: "Sad", ayahs: 88, juz: 23, type: "Makkiyah" },
  { number: 39, latin: "Az-Zumar", name: "الزمر", meaning: "Rombongan", ayahs: 75, juz: 23, type: "Makkiyah" },
  { number: 40, latin: "Ghafir", name: "غافر", meaning: "Yang Mengampuni", ayahs: 85, juz: 24, type: "Makkiyah" },
  { number: 41, latin: "Fussilat", name: "فصلت", meaning: "Yang Dijelaskan", ayahs: 54, juz: 24, type: "Makkiyah" },
  { number: 42, latin: "Asy-Syura", name: "الشورى", meaning: "Musyawarah", ayahs: 53, juz: 25, type: "Makkiyah" },
  { number: 43, latin: "Az-Zukhruf", name: "الزخرف", meaning: "Perhiasan", ayahs: 89, juz: 25, type: "Makkiyah" },
  { number: 44, latin: "Ad-Dukhan", name: "الدخان", meaning: "Kabut", ayahs: 59, juz: 25, type: "Makkiyah" },
  { number: 45, latin: "Al-Jasiyah", name: "الجاثية", meaning: "Yang Berlutut", ayahs: 37, juz: 25, type: "Makkiyah" },
  { number: 46, latin: "Al-Ahqaf", name: "الأحقاف", meaning: "Bukit Pasir", ayahs: 35, juz: 26, type: "Makkiyah" },
  { number: 47, latin: "Muhammad", name: "محمد", meaning: "Nabi Muhammad", ayahs: 38, juz: 26, type: "Madaniyah" },
  { number: 48, latin: "Al-Fath", name: "الفتح", meaning: "Kemenangan", ayahs: 29, juz: 26, type: "Madaniyah" },
  { number: 49, latin: "Al-Hujurat", name: "الحجرات", meaning: "Kamar-Kamar", ayahs: 18, juz: 26, type: "Madaniyah" },
  { number: 50, latin: "Qaf", name: "ق", meaning: "Qaf", ayahs: 45, juz: 26, type: "Makkiyah" },
  { number: 51, latin: "Az-Zariyat", name: "الذاريات", meaning: "Angin yang Menerbangkan", ayahs: 60, juz: 26, type: "Makkiyah" },
  { number: 52, latin: "At-Tur", name: "الطور", meaning: "Bukit", ayahs: 49, juz: 27, type: "Makkiyah" },
  { number: 53, latin: "An-Najm", name: "النجم", meaning: "Bintang", ayahs: 62, juz: 27, type: "Makkiyah" },
  { number: 54, latin: "Al-Qamar", name: "القمر", meaning: "Bulan", ayahs: 55, juz: 27, type: "Makkiyah" },
  { number: 55, latin: "Ar-Rahman", name: "الرحمن", meaning: "Yang Maha Pemurah", ayahs: 78, juz: 27, type: "Madaniyah" },
  { number: 56, latin: "Al-Waqi'ah", name: "الواقعة", meaning: "Hari Kiamat", ayahs: 96, juz: 27, type: "Makkiyah" },
  { number: 57, latin: "Al-Hadid", name: "الحديد", meaning: "Besi", ayahs: 29, juz: 27, type: "Madaniyah" },
  { number: 58, latin: "Al-Mujadilah", name: "المجادلة", meaning: "Wanita yang Menggugat", ayahs: 22, juz: 28, type: "Madaniyah" },
  { number: 59, latin: "Al-Hasyr", name: "الحشر", meaning: "Pengusiran", ayahs: 24, juz: 28, type: "Madaniyah" },
  { number: 60, latin: "Al-Mumtahanah", name: "الممتحنة", meaning: "Wanita yang Diuji", ayahs: 13, juz: 28, type: "Madaniyah" },
  { number: 61, latin: "As-Saff", name: "الصف", meaning: "Barisan", ayahs: 14, juz: 28, type: "Madaniyah" },
  { number: 62, latin: "Al-Jumu'ah", name: "الجمعة", meaning: "Hari Jumat", ayahs: 11, juz: 28, type: "Madaniyah" },
  { number: 63, latin: "Al-Munafiqun", name: "المنافقون", meaning: "Orang-Orang Munafik", ayahs: 11, juz: 28, type: "Madaniyah" },
  { number: 64, latin: "At-Tagabun", name: "التغابن", meaning: "Hari Ditampakkan Kesalahan", ayahs: 18, juz: 28, type: "Madaniyah" },
  { number: 65, latin: "At-Talaq", name: "الطلاق", meaning: "Talak", ayahs: 12, juz: 28, type: "Madaniyah" },
  { number: 66, latin: "At-Tahrim", name: "التحريم", meaning: "Mengharamkan", ayahs: 12, juz: 28, type: "Madaniyah" },
  { number: 67, latin: "Al-Mulk", name: "الملك", meaning: "Kerajaan", ayahs: 30, juz: 29, type: "Makkiyah" },
  { number: 68, latin: "Al-Qalam", name: "القلم", meaning: "Pena", ayahs: 52, juz: 29, type: "Makkiyah" },
  { number: 69, latin: "Al-Haqqah", name: "الحاقة", meaning: "Hari Kiamat", ayahs: 52, juz: 29, type: "Makkiyah" },
  { number: 70, latin: "Al-Ma'arij", name: "المعارج", meaning: "Tempat Naik", ayahs: 44, juz: 29, type: "Makkiyah" },
  { number: 71, latin: "Nuh", name: "نوح", meaning: "Nabi Nuh", ayahs: 28, juz: 29, type: "Makkiyah" },
  { number: 72, latin: "Al-Jinn", name: "الجن", meaning: "Jin", ayahs: 28, juz: 29, type: "Makkiyah" },
  { number: 73, latin: "Al-Muzzammil", name: "المزمل", meaning: "Orang yang Berselimut", ayahs: 20, juz: 29, type: "Makkiyah" },
  { number: 74, latin: "Al-Muddassir", name: "المدثر", meaning: "Orang yang Berkemul", ayahs: 56, juz: 29, type: "Makkiyah" },
  { number: 75, latin: "Al-Qiyamah", name: "القيامة", meaning: "Hari Kiamat", ayahs: 40, juz: 29, type: "Makkiyah" },
  { number: 76, latin: "Al-Insan", name: "الانسان", meaning: "Manusia", ayahs: 31, juz: 29, type: "Madaniyah" },
  { number: 77, latin: "Al-Mursalat", name: "المرسلات", meaning: "Malaikat Yang Diutus", ayahs: 50, juz: 29, type: "Makkiyah" },
  { number: 78, latin: "An-Naba'", name: "النبأ", meaning: "Berita Besar", ayahs: 40, juz: 30, type: "Makkiyah" },
  { number: 79, latin: "An-Nazi'at", name: "النازعات", meaning: "Malaikat Pencabut", ayahs: 46, juz: 30, type: "Makkiyah" },
  { number: 80, latin: "Abasa", name: "عبس", meaning: "Ia Bermuka Masam", ayahs: 42, juz: 30, type: "Makkiyah" },
  { number: 81, latin: "At-Takwir", name: "التكوير", meaning: "Menggulung", ayahs: 29, juz: 30, type: "Makkiyah" },
  { number: 82, latin: "Al-Infitar", name: "الإنفطار", meaning: "Terbelah", ayahs: 19, juz: 30, type: "Makkiyah" },
  { number: 83, latin: "Al-Mutaffifin", name: "المطففين", meaning: "Orang-Orang Curang", ayahs: 36, juz: 30, type: "Makkiyah" },
  { number: 84, latin: "Al-Insyiqaq", name: "الإنشقاق", meaning: "Terbelah", ayahs: 25, juz: 30, type: "Makkiyah" },
  { number: 85, latin: "Al-Buruj", name: "البروج", meaning: "Gugusan Bintang", ayahs: 22, juz: 30, type: "Makkiyah" },
  { number: 86, latin: "At-Tariq", name: "الطارق", meaning: "Yang Datang di Malam Hari", ayahs: 17, juz: 30, type: "Makkiyah" },
  { number: 87, latin: "Al-A'la", name: "الأعلى", meaning: "Yang Paling Tinggi", ayahs: 19, juz: 30, type: "Makkiyah" },
  { number: 88, latin: "Al-Ghasyiyah", name: "الغاشية", meaning: "Hari Pembalasan", ayahs: 26, juz: 30, type: "Makkiyah" },
  { number: 89, latin: "Al-Fajr", name: "الفجر", meaning: "Fajar", ayahs: 30, juz: 30, type: "Makkiyah" },
  { number: 90, latin: "Al-Balad", name: "البلد", meaning: "Negeri", ayahs: 20, juz: 30, type: "Makkiyah" },
  { number: 91, latin: "Asy-Syams", name: "الشمس", meaning: "Matahari", ayahs: 15, juz: 30, type: "Makkiyah" },
  { number: 92, latin: "Al-Lail", name: "الليل", meaning: "Malam", ayahs: 21, juz: 30, type: "Makkiyah" },
  { number: 93, latin: "Ad-Duha", name: "الضحى", meaning: "Waktu Duha", ayahs: 11, juz: 30, type: "Makkiyah" },
  { number: 94, latin: "Asy-Syarh", name: "الشرح", meaning: "Melapangkan", ayahs: 8, juz: 30, type: "Makkiyah" },
  { number: 95, latin: "At-Tin", name: "التين", meaning: "Buah Tin", ayahs: 8, juz: 30, type: "Makkiyah" },
  { number: 96, latin: "Al-'Alaq", name: "العلق", meaning: "Segumpal Darah", ayahs: 19, juz: 30, type: "Makkiyah" },
  { number: 97, latin: "Al-Qadr", name: "القدر", meaning: "Kemuliaan", ayahs: 5, juz: 30, type: "Makkiyah" },
  { number: 98, latin: "Al-Bayyinah", name: "البينة", meaning: "Bukti", ayahs: 8, juz: 30, type: "Madaniyah" },
  { number: 99, latin: "Az-Zalzalah", name: "الزلزلة", meaning: "Kegoncangan", ayahs: 8, juz: 30, type: "Madaniyah" },
  { number: 100, latin: "Al-'Adiyat", name: "العاديات", meaning: "Kuda Perang", ayahs: 11, juz: 30, type: "Makkiyah" },
  { number: 101, latin: "Al-Qari'ah", name: "القارعة", meaning: "Hari Kiamat", ayahs: 11, juz: 30, type: "Makkiyah" },
  { number: 102, latin: "At-Takatsur", name: "التكاثر", meaning: "Bermegah-Megahan", ayahs: 8, juz: 30, type: "Makkiyah" },
  { number: 103, latin: "Al-'Asr", name: "العصر", meaning: "Masa", ayahs: 3, juz: 30, type: "Makkiyah" },
  { number: 104, latin: "Al-Humazah", name: "الهمزة", meaning: "Pengumpat", ayahs: 9, juz: 30, type: "Makkiyah" },
  { number: 105, latin: "Al-Fil", name: "الفيل", meaning: "Gajah", ayahs: 5, juz: 30, type: "Makkiyah" },
  { number: 106, latin: "Quraisy", name: "قريش", meaning: "Suku Quraisy", ayahs: 4, juz: 30, type: "Makkiyah" },
  { number: 107, latin: "Al-Ma'un", name: "الماعون", meaning: "Barang-Barang Berguna", ayahs: 7, juz: 30, type: "Makkiyah" },
  { number: 108, latin: "Al-Kautsar", name: "الكوثر", meaning: "Nikmat yang Banyak", ayahs: 3, juz: 30, type: "Makkiyah" },
  { number: 109, latin: "Al-Kafirun", name: "الكافرون", meaning: "Orang-Orang Kafir", ayahs: 6, juz: 30, type: "Makkiyah" },
  { number: 110, latin: "An-Nasr", name: "النصر", meaning: "Pertolongan", ayahs: 3, juz: 30, type: "Madaniyah" },
  { number: 111, latin: "Al-Lahab", name: "اللهب", meaning: "Gejolak Api", ayahs: 5, juz: 30, type: "Makkiyah" },
  { number: 112, latin: "Al-Ikhlas", name: "الإخلاص", meaning: "Ikhlas", ayahs: 4, juz: 30, type: "Makkiyah" },
  { number: 113, latin: "Al-Falaq", name: "الفلق", meaning: "Waktu Subuh", ayahs: 5, juz: 30, type: "Makkiyah" },
  { number: 114, latin: "An-Nas", name: "الناس", meaning: "Manusia", ayahs: 6, juz: 30, type: "Makkiyah" }
];

export const DALIL_DATA: DalilTopic[] = [
  {
    id: 'puasa',
    title: 'Puasa',
    description: 'Ayat-ayat Al-Quran tentang perintah dan keutamaan puasa.',
    color: 'bg-emerald-500',
    icon: null, // We'll handle SVG in component
    verses: [
      { surahNumber: 2, ayah: "183", description: "Perintah wajib puasa bagi orang beriman" },
      { surahNumber: 2, ayah: "185", description: "Ramadhan sebagai bulan diturunkannya Al-Quran" },
      { surahNumber: 2, ayah: "187", description: "Hukum-hukum seputar puasa (makan, minum, hubungan suami istri)" }
    ]
  },
  {
    id: 'shalat',
    title: 'Shalat',
    description: 'Dalil mengenai kewajiban mendirikan shalat.',
    color: 'bg-indigo-500',
    icon: null,
    verses: [
      { surahNumber: 2, ayah: "43", description: "Perintah mendirikan shalat dan menunaikan zakat" },
      { surahNumber: 20, ayah: "14", description: "Mendirikan shalat untuk mengingat Allah" },
      { surahNumber: 29, ayah: "45", description: "Shalat mencegah perbuatan keji dan mungkar" },
      { surahNumber: 4, ayah: "103", description: "Kewajiban shalat pada waktu yang ditentukan" }
    ]
  }
];